import { z } from 'zod';
export const organizationRoleSchema=z.enum(['OWNER','ADMIN','CONTRACT_MANAGER','LEGAL_OFFICER','DEPARTMENT_MANAGER','FINANCE_OFFICER','PROCUREMENT_OFFICER','CONTRACT_OWNER','AUDITOR','VIEWER']);
export const organizationSchema=z.object({id:z.uuid(),slug:z.string(),name:z.string(),status:z.enum(['ACTIVE','SUSPENDED'])});
export const departmentSchema=z.object({id:z.uuid(),organizationId:z.uuid(),parentId:z.uuid().nullable(),code:z.string(),name:z.string(),isActive:z.boolean()});
export const invitationSchema=z.object({id:z.uuid(),organizationId:z.uuid(),email:z.email(),role:organizationRoleSchema,status:z.enum(['PENDING','ACCEPTED','EXPIRED','REVOKED']),expiresAt:z.iso.datetime()});
export const auditEventSchema=z.object({id:z.uuid(),organizationId:z.uuid(),actorUserId:z.uuid().nullable(),action:z.string(),entityType:z.string(),entityId:z.string().nullable(),createdAt:z.iso.datetime()});
export const contractRequestStatusSchema=z.enum(['DRAFT','SUBMITTED','TRIAGED','CONVERTED','CANCELLED']);
export const contractStatusSchema=z.enum(['DRAFT','IN_REVIEW','CHANGES_REQUESTED','APPROVED','ACTIVE','CANCELLED']);
export const contractRiskLevelSchema=z.enum(['LOW','MEDIUM','HIGH']);
export const contractRequestSchema=z.object({id:z.uuid(),organizationId:z.uuid(),departmentId:z.uuid(),requestNumber:z.string(),title:z.string(),contractType:z.string(),counterpartyName:z.string(),estimatedValueMinor:z.string().nullable(),currency:z.string().length(3),riskLevel:contractRiskLevelSchema,status:contractRequestStatusSchema});
export const contractSchema=z.object({id:z.uuid(),organizationId:z.uuid(),requestId:z.uuid().nullable(),departmentId:z.uuid(),ownerMembershipId:z.uuid(),contractNumber:z.string(),title:z.string(),contractType:z.string(),counterpartyName:z.string(),valueMinor:z.string().nullable(),currency:z.string().length(3),riskLevel:contractRiskLevelSchema,status:contractStatusSchema});
export const reviewStepSchema=z.object({id:z.uuid(),contractId:z.uuid(),round:z.number().int().positive(),sequence:z.number().int().positive(),name:z.string(),requiredRole:organizationRoleSchema,status:z.enum(['PENDING','APPROVED','CHANGES_REQUESTED','SKIPPED'])});
