const copy={
  en:{demo:'Development showcase · Sample data · No real authentication',dashboard:'Dashboard',contracts:'Contracts',approvals:'Approvals',obligations:'Obligations',organization:'Organization',reports:'Reports',workspace:'Development workspace',setup:'Workspace setup · 72%',search:'Search contracts, parties, or IDs…',overview:'Overview',welcome:'Good morning, Danny',welcomeSub:'Here’s what needs your attention across the contract portfolio.',newContract:'New contract',activeContracts:'Active contracts',fromMonth:'from last month',portfolioValue:'Portfolio value',across:'Across 8 departments',pendingApprovals:'Pending approvals',twoUrgent:'2 require attention today',expiringSoon:'Expiring soon',nextDays:'Within the next 30 days',portfolio:'Contract portfolio',portfolioSub:'Active value by department',thisYear:'This year⌄',totalValue:'Total value',procurement:'Procurement',operations:'Operations',hr:'Human resources',other:'Other',attention:'Needs attention',attentionSub:'Deadlines and pending actions',viewAll:'View all',expires3:'Expires in 3 days',awaitLegal:'Awaiting legal approval',milestoneDue:'Payment milestone due Aug 06',recent:'Recent contracts',recentSub:'Latest activity across your organization',viewContracts:'View all contracts',contract:'Contract',counterparty:'Counterparty',department:'Department',value:'Value',expiry:'Expiry',status:'Status',repository:'Repository',allContracts:'All contracts',contractsSub:'Search, filter, and manage your organization’s agreements.',filter:'Filter contracts…',filterButton:'Filters',export:'Export',owner:'Owner',workflow:'Workflow',approvalQueue:'Approval queue',approvalSub:'Review decisions waiting for your role.',tracking:'Tracking',obligationTitle:'Obligations & milestones',obligationSub:'Stay ahead of deliverables, payments, and commitments.',dueSoon:'Due soon',inProgress:'In progress',completed:'Completed',administration:'Administration',orgTitle:'Organization & access',orgSub:'Memberships and roles are enforced inside every workspace.',invite:'Invite member',active:'Active',members:'Members',membersSub:'8 active members across 5 roles',insights:'Insights',reportTitle:'Portfolio reports',reportSub:'A concise view of value, risk, and contract activity.',downloadReport:'Download report',activity:'Contract activity',riskProfile:'Risk profile',low:'Low risk',medium:'Medium risk',high:'High risk'},
  am:{demo:'የሙከራ ማሳያ · ናሙና መረጃ · እውነተኛ መግቢያ የለም',dashboard:'ዳሽቦርድ',contracts:'ውሎች',approvals:'ማጽደቂያዎች',obligations:'ግዴታዎች',organization:'ድርጅት',reports:'ሪፖርቶች',workspace:'የሙከራ የስራ ቦታ',setup:'የስራ ቦታ ዝግጅት · 72%',search:'ውል፣ ተዋዋይ ወይም መለያ ይፈልጉ…',overview:'አጠቃላይ እይታ',welcome:'እንደምን አደርክ፣ ዳኒ',welcomeSub:'በውል ስብስቡ ውስጥ ትኩረትዎን የሚፈልጉ ጉዳዮች።',newContract:'አዲስ ውል',activeContracts:'ንቁ ውሎች',fromMonth:'ካለፈው ወር ጀምሮ',portfolioValue:'የውል ጠቅላላ ዋጋ',across:'በ8 የስራ ክፍሎች',pendingApprovals:'የሚጠበቁ ማጽደቂያዎች',twoUrgent:'2 ዛሬ ትኩረት ይፈልጋሉ',expiringSoon:'በቅርቡ የሚያልቁ',nextDays:'በሚቀጥሉት 30 ቀናት',portfolio:'የውል ስብስብ',portfolioSub:'በስራ ክፍል የንቁ ውሎች ዋጋ',thisYear:'ይህ ዓመት⌄',totalValue:'ጠቅላላ ዋጋ',procurement:'ግዥ',operations:'ኦፕሬሽን',hr:'የሰው ኃይል',other:'ሌላ',attention:'ትኩረት የሚፈልጉ',attentionSub:'የጊዜ ገደቦች እና የሚጠበቁ ተግባራት',viewAll:'ሁሉንም ይመልከቱ',expires3:'በ3 ቀናት ውስጥ ያልቃል',awaitLegal:'የህግ ማጽደቂያ ይጠብቃል',milestoneDue:'የክፍያ ጊዜ ነሐሴ 06',recent:'የቅርብ ጊዜ ውሎች',recentSub:'በድርጅቱ ውስጥ የቅርብ ጊዜ እንቅስቃሴ',viewContracts:'ሁሉንም ውሎች ይመልከቱ',contract:'ውል',counterparty:'ተዋዋይ',department:'የስራ ክፍል',value:'ዋጋ',expiry:'የሚያልቅበት',status:'ሁኔታ',repository:'ማከማቻ',allContracts:'ሁሉም ውሎች',contractsSub:'የድርጅትዎን ውሎች ይፈልጉ፣ ያጣሩ እና ያስተዳድሩ።',filter:'ውሎችን ያጣሩ…',filterButton:'ማጣሪያ',export:'ወደ ውጭ ላክ',owner:'ባለቤት',workflow:'የስራ ፍሰት',approvalQueue:'የማጽደቂያ ዝርዝር',approvalSub:'የእርስዎን ውሳኔ የሚጠብቁ ውሎች።',tracking:'ክትትል',obligationTitle:'ግዴታዎች እና ወሳኝ ደረጃዎች',obligationSub:'የሚፈጸሙ ስራዎችን፣ ክፍያዎችን እና ቃል ኪዳኖችን ይከታተሉ።',dueSoon:'በቅርቡ የሚደርሱ',inProgress:'በሂደት ላይ',completed:'የተጠናቀቁ',administration:'አስተዳደር',orgTitle:'ድርጅት እና መዳረሻ',orgSub:'አባልነት እና ሚና በየስራ ቦታው ይተገበራሉ።',invite:'አባል ጋብዝ',active:'ንቁ',members:'አባላት',membersSub:'በ5 ሚናዎች 8 ንቁ አባላት',insights:'ግንዛቤዎች',reportTitle:'የውል ስብስብ ሪፖርቶች',reportSub:'የዋጋ፣ ስጋት እና የውል እንቅስቃሴ አጭር እይታ።',downloadReport:'ሪፖርት አውርድ',activity:'የውል እንቅስቃሴ',riskProfile:'የስጋት ደረጃ',low:'ዝቅተኛ ስጋት',medium:'መካከለኛ ስጋት',high:'ከፍተኛ ስጋት'}
};

Object.assign(copy.en,{departments:'Departments',hierarchyActive:'Hierarchy active',pendingInvites:'Pending invitations',expireSeven:'Expire in 7 days',auditEvents:'Audit events',appendOnly:'Append-only history',ownership:'Ownership',transferOwner:'Transfer safely →',departmentSub:'Structure, managers, and member assignments',addDepartment:'Add department',invitationSub:'Secure, expiring access links',recentAudit:'Recent audit activity',auditSub:'Immutable organization-management history'});
Object.assign(copy.am,{departments:'የስራ ክፍሎች',hierarchyActive:'የተዋረድ መዋቅር ንቁ ነው',pendingInvites:'የሚጠበቁ ግብዣዎች',expireSeven:'በ7 ቀናት ያልቃሉ',auditEvents:'የኦዲት ክስተቶች',appendOnly:'የማይቀየር ታሪክ',ownership:'ባለቤትነት',transferOwner:'በደህና ያስተላልፉ →',departmentSub:'መዋቅር፣ ኃላፊዎች እና የአባል ምደባ',addDepartment:'የስራ ክፍል ጨምር',invitationSub:'ደህንነቱ የተጠበቀ ጊዜያዊ የመዳረሻ አገናኝ',recentAudit:'የቅርብ ጊዜ የኦዲት እንቅስቃሴ',auditSub:'የማይቀየር የድርጅት አስተዳደር ታሪክ'});
Object.assign(copy.en,{requests:'Requests',intake:'Intake',requestTitle:'Contract requests',requestSub:'Capture business needs, triage risk, and convert approved intake into controlled contracts.',newRequest:'New request',draftStage:'Draft',submittedStage:'Submitted',triagedStage:'Triaged',convertedStage:'Converted',intakeQueue:'Intake queue',intakeQueueSub:'Requests awaiting triage and assignment',risk:'Risk',assignee:'Assignee',convertContract:'Convert to contract'});
Object.assign(copy.am,{requests:'ጥያቄዎች',intake:'መቀበያ',requestTitle:'የውል ጥያቄዎች',requestSub:'የንግድ ፍላጎትን ይመዝግቡ፣ ስጋትን ይመድቡ እና የጸደቀውን ጥያቄ ወደ ቁጥጥር ያለው ውል ይቀይሩ።',newRequest:'አዲስ ጥያቄ',draftStage:'ረቂቅ',submittedStage:'የቀረበ',triagedStage:'የተመደበ',convertedStage:'ወደ ውል የተቀየረ',intakeQueue:'የጥያቄ ወረፋ',intakeQueueSub:'ምደባ እና የስጋት ግምገማ የሚጠብቁ ጥያቄዎች',risk:'ስጋት',assignee:'ተመዳቢ',convertContract:'ወደ ውል ቀይር'});

const contracts=[
  {id:'KF-2026-024',name:'Enterprise connectivity service',party:'Ethio Telecom',dept:'IT & Digital',owner:'Henok B.',value:'ETB 2.4M',expiry:'Aug 04, 2026',status:'expiring'},
  {id:'KF-2026-019',name:'Industrial equipment supply',party:'East Africa Trading PLC',dept:'Procurement',owner:'Alem T.',value:'ETB 12.8M',expiry:'Dec 18, 2026',status:'active'},
  {id:'KF-2026-017',name:'Freight forwarding framework',party:'Abyssinia Logistics',dept:'Operations',owner:'Betelhem G.',value:'ETB 6.2M',expiry:'Mar 21, 2027',status:'review'},
  {id:'KF-2026-014',name:'Employee medical insurance',party:'Nyala Insurance S.C.',dept:'Human Resources',owner:'Samson K.',value:'ETB 3.7M',expiry:'Jun 30, 2027',status:'active'},
  {id:'KF-2026-011',name:'Warehouse lease agreement',party:'Addis Property Group',dept:'Operations',owner:'Alem T.',value:'ETB 8.5M',expiry:'Jan 15, 2027',status:'active'},
  {id:'KF-2026-009',name:'Legal advisory retainer',party:'Tadesse Kiros Law Office',dept:'Legal',owner:'Marta S.',value:'ETB 1.2M',expiry:'Sep 01, 2026',status:'draft'}
];
const approvals=[
  {type:'LEGAL REVIEW',name:'Freight forwarding framework',desc:'Review liability limits and termination clauses before final approval.',owner:'Betelhem Girma',value:'ETB 6.2M',due:'Today'},
  {type:'FINANCE APPROVAL',name:'Industrial equipment supply',desc:'Verify payment schedule and advance-payment guarantee.',owner:'Alem Tesfaye',value:'ETB 12.8M',due:'Aug 03'},
  {type:'MANAGER APPROVAL',name:'Warehouse lease agreement',desc:'Confirm operational requirements and three-year commitment.',owner:'Alem Tesfaye',value:'ETB 8.5M',due:'Aug 05'}
];
const members=[['DN','Danny New','danny@kalflow.local','Owner'],['MS','Marta Seyoum','marta@kalflow.local','Legal Officer'],['AT','Alem Tesfaye','alem@kalflow.local','Contract Admin'],['HG','Henok Bekele','henok@kalflow.local','Department Manager'],['BG','Betelhem Girma','betelhem@kalflow.local','Procurement'],['SK','Samson Kebede','samson@kalflow.local','Viewer']];
const departments=[['PROC','Procurement','Betelhem Girma · 3 members'],['OPS','Operations','Alem Tesfaye · 2 members'],['LEGAL','Legal','Marta Seyoum · 1 member'],['HR','Human Resources','Samson Kebede · 2 members'],['IT','IT & Digital','Henok Bekele · 2 members']];
const invitations=[['selam@kalflow.local','Finance Officer','Expires Aug 09'],['yonas@kalflow.local','Contract Manager','Expires Aug 09']];
const auditEvents=[['Ownership transfer policy reviewed','Danny New','2 min ago'],['PROC department membership updated','Henok Bekele','18 min ago'],['Invitation sent to selam@kalflow.local','Danny New','1 hr ago'],['Organization settings updated','Danny New','Yesterday']];
const requests=[
  ['KF-REQ-2026-04F10A2C','Fleet maintenance framework','Abay Automotive Services','Operations','ETB 4.8M','Medium','Triaged'],
  ['KF-REQ-2026-A1359F20','Office security services','Sheger Security PLC','Administration','ETB 1.6M','Low','Submitted'],
  ['KF-REQ-2026-7CE40B11','Raw material supply','Blue Nile Polymers','Procurement','ETB 18.2M','High','Submitted'],
  ['KF-REQ-2026-F8D3039A','Payroll software subscription','Addis Systems SC','IT & Digital','ETB 980K','Medium','Draft']
];
let language='en';

function statusLabel(status){return {active:'Active',review:'In review',draft:'Draft',expiring:'Expiring'}[status]||status}
function contractRow(c,recent=false){return `<tr><td><div class="contract-name"><strong>${c.name}</strong><small>${c.id}</small></div></td><td>${c.party}</td><td>${c.dept}</td>${recent?'':`<td>${c.owner}</td>`}<td>${c.value}</td>${recent?`<td>${c.expiry}</td>`:''}<td><span class="badge ${c.status}">${statusLabel(c.status)}</span></td></tr>`}
function renderContracts(filter=''){const list=contracts.filter(c=>Object.values(c).join(' ').toLowerCase().includes(filter.toLowerCase()));document.querySelector('#contractRows').innerHTML=list.map(c=>contractRow(c)).join('');document.querySelector('#recentRows').innerHTML=contracts.slice(0,4).map(c=>contractRow(c,true)).join('')}
function renderApprovals(){document.querySelector('#approvalCards').innerHTML=approvals.map(a=>`<article class="panel approval-card"><span class="tag">${a.type}</span><h2>${a.name}</h2><p>${a.desc}</p><div class="approval-meta"><span><em>Requested by</em><b>${a.owner}</b></span><span><em>Contract value</em><b>${a.value}</b></span><span><em>Due</em><b>${a.due}</b></span></div><div class="approval-actions"><button class="ghost danger-outline" data-action="reject">Request changes</button><button class="primary" data-action="approve">Approve</button></div></article>`).join('')}
function renderMembers(){document.querySelector('#memberCards').innerHTML=members.map(m=>`<div class="member"><span class="member-avatar">${m[0]}</span><span><strong>${m[1]}</strong><small>${m[2]}</small></span><span class="role">${m[3]}</span></div>`).join('')}
function renderOrganization(){document.querySelector('#departmentCards').innerHTML=departments.map(d=>`<div class="department-row"><span class="department-code">${d[0]}</span><span><strong>${d[1]}</strong><small>${d[2]}</small></span><span>Active</span></div>`).join('');document.querySelector('#invitationCards').innerHTML=invitations.map(i=>`<div class="invitation-row"><span><strong>${i[0]}</strong><small>${i[1]} · ${i[2]}</small></span><span class="badge review">Pending</span></div>`).join('');document.querySelector('#auditCards').innerHTML=auditEvents.map(a=>`<div class="audit-row"><i></i><span><strong>${a[0]}</strong> · ${a[1]}</span><time>${a[2]}</time></div>`).join('')}
function renderRequests(){document.querySelector('#requestCards').innerHTML=requests.map((r,index)=>`<button class="request-row ${index===0?'selected':''}" data-action="select-request"><span><strong>${r[1]}</strong><small>${r[0]} · ${r[2]}</small></span><span><b>${r[4]}</b><small>${r[3]} · ${r[5]} risk</small></span><span class="badge ${r[6]==='Draft'?'draft':'review'}">${r[6]}</span></button>`).join('')}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===id));document.querySelector('#sidebar').classList.remove('open');window.scrollTo(0,0);history.replaceState(null,'',`#${id}`)}
function updateLanguage(){document.documentElement.lang=language;document.querySelectorAll('[data-copy]').forEach(el=>{const key=el.dataset.copy;if(copy[language][key])el.textContent=copy[language][key]});document.querySelectorAll('[data-copy-placeholder]').forEach(el=>{const key=el.dataset.copyPlaceholder;if(copy[language][key])el.placeholder=copy[language][key]});document.querySelector('#languageButton').textContent=language==='en'?'አማ':'EN'}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}

renderContracts();renderApprovals();renderMembers();renderOrganization();renderRequests();
document.querySelectorAll('[data-view],[data-view-target]').forEach(el=>el.addEventListener('click',()=>showView(el.dataset.view||el.dataset.viewTarget)));
document.querySelector('#contractSearch').addEventListener('input',e=>renderContracts(e.target.value));
document.querySelector('#languageButton').addEventListener('click',()=>{language=language==='en'?'am':'en';updateLanguage()});
document.querySelector('#menuButton').addEventListener('click',()=>document.querySelector('#sidebar').classList.toggle('open'));
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='new-contract'||action==='request')showView('requests');if(action==='convert')toast('Demo mode: request converted to a draft contract with a complete audit event.');if(action==='select-request')toast('Request selected. The live API enforces organization scope and lifecycle state.');if(action==='invite')toast('Invitation lifecycle is implemented in the API; email delivery follows in staging.');if(action==='department')toast('Department hierarchy and assignments are implemented in the API.');if(action==='transfer')toast('Ownership transfer requires owner permission and completes atomically.');if(action==='approve')toast('Demo mode: approval recorded locally for this preview.');if(action==='reject')toast('Demo mode: change request opened locally.')});
const initial=location.hash.slice(1);if(document.getElementById(initial))showView(initial);
